source 'https://rubygems.org'

gem 'dotenv'
gem 'json'
gem 'pry'
gem 'ffi'
gem 'rake'
gem 'will_paginate'
gem 'rest-client'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-static-assets'

group :development do
  gem 'foreman'
  gem 'rubocop'
  gem 'sqlite3', '~> 1.3', '>= 1.3.11'
end

group :production do
  gem 'pg'
end

gem "rackup", "~> 2.1"
